class LocalStrings {
  static const Map<String, Map<String, String>> _data = {
    'welcome_text': {
      'ru':
          'Приложение для тех, кто хочет совершить Умру самостоятельно. Пошаговое сопровождение на каждом этапе. От намерения до полного завершения Умры. Без путаницы и лишних посредников. Спокойно. Осознанно. Правильно.',
      'uz':
          'Umrani mustaqil ado etishni istaganlar uchun ilova. Har bir bosqichda qadam-baqadam yo\'riqnoma. Niyatdan Umrani to\'liq yakunlashgacha. Chalkashliksiz va ortiqcha vositachilarsiz. Xotirjam. Ongli. To\'g\'ri.',
      'kz':
          'Умраны өз бетінше орындағысы келетіндерге арналған қосымша. Әр кезеңде қадамдап бағыттау. Ниеттен Умраны толық аяқтауға дейін. Артық шатасусыз және делдалдарсыз. Сабырмен. Саналы түрде. Дұрыс.',
      'id':
          'Aplikasi untuk mereka yang ingin menunaikan Umrah secara mandiri. Panduan langkah demi langkah di setiap tahap. Dari niat hingga Umrah selesai sepenuhnya. Tanpa kebingungan dan tanpa perantara yang tidak perlu. Tenang. Sadar. Benar.',
      'tr':
          'Umreyi kendi basina yapmak isteyenler icin bir uygulama. Her asamada adim adim rehberlik. Niyetten Umrenin tamamen tamamlanmasina kadar. Karmasa ve gereksiz aracilar olmadan. Sakin. Bilincli. Dogru.',
      'ms':
          'Aplikasi untuk mereka yang ingin menunaikan Umrah secara sendiri. Panduan langkah demi langkah di setiap peringkat. Dari niat hingga Umrah selesai sepenuhnya. Tanpa kekeliruan dan tanpa perantara yang tidak perlu. Tenang. Sedar. Betul.',
      'bn':
          'যারা নিজের উদ্যোগে উমরাহ আদায় করতে চান তাদের জন্য একটি অ্যাপ। প্রতিটি ধাপে ধাপে নির্দেশনা। নিয়ত থেকে উমরাহ সম্পূর্ণ হওয়া পর্যন্ত। কোনো বিভ্রান্তি ও অপ্রয়োজনীয় মধ্যস্থতাকারী ছাড়া। শান্তভাবে। সচেতনভাবে। সঠিকভাবে।',
      'en':
          'An app for those who want to perform Umrah independently. Step by step guidance at every stage. From intention to full completion of Umrah. No confusion and no unnecessary intermediaries. Calm. Mindful. Correct.',
      'fr':
          'Une application pour ceux qui souhaitent accomplir l Omra de maniere autonome. Un accompagnement etape par etape a chaque phase. De l intention jusqu a l accomplissement complet de l Omra. Sans confusion ni intermediaires inutiles. Calme. Conscient. Juste.',
    },
    'welcome_button': {
      'ru': 'Начать',
      'uz': 'Boshlash',
      'kz': 'Бастау',
      'id': 'Mulai',
      'tr': 'Başla',
      'ms': 'Mula',
      'bn': 'শুরু করুন',
      'en': 'Start',
      'fr': 'Commencer',
    },
    'welcome_subtitle_1': {
      'ru': 'Добро пожаловать!',
      'uz': 'Xush kelibsiz!',
      'kz': 'Қош келдіңіз!',
      'id': 'Selamat datang!',
      'tr': 'Hoş geldiniz!',
      'ms': 'Selamat datang!',
      'bn': 'স্বাগতম!',
      'en': 'Welcome!',
      'fr': 'Bienvenue !',
    },
    'register_title': {
      'ru': 'Регистрация',
      'uz': 'Ro‘yxatdan o‘tish',
      'kz': 'Тіркелу',
      'id': 'Registrasi',
      'tr': 'Kayıt Ol',
      'ms': 'Daftar',
      'bn': 'নিবন্ধন',
      'en': 'Register',
      'fr': 'Inscription',
    },
    'register_subtitle_1': {
      'ru': 'Добро пожаловать!',
      'uz': 'Xush kelibsiz!',
      'kz': 'Қош келдіңіз!',
      'id': 'Selamat datang!',
      'tr': 'Hoş geldiniz!',
      'ms': 'Selamat datang!',
      'bn': 'স্বাগতম!',
      'en': 'Welcome!',
      'fr': 'Bienvenue !',
    },
    'register_subtitle_2': {
      'ru': 'Ваше путешествие начинается здесь!',
      'uz': 'Sizning sayohatingiz aynan shu yerda boshlanadi!',
      'kz': 'Сіздің сапарыңыз дәл осы жерден басталады!',
      'id': 'Perjalanan Anda dimulai di sini!',
      'tr': 'Yolculuğunuz burada başlıyor!',
      'ms': 'Perjalanan anda bermula di sini!',
      'bn': 'আপনার যাত্রা এখানেই শুরু!',
      'en': 'Your journey begins here!',
      'fr': 'Votre voyage commence ici !',
    },
    'register_email': {
      'ru': 'Email',
      'uz': 'Email',
      'kz': 'Email',
      'id': 'Email',
      'tr': 'E-posta',
      'ms': 'Email',
      'bn': 'ইমেইল',
      'en': 'Email',
      'fr': 'E-mail',
    },
    'register_password': {
      'ru': 'Пароль',
      'uz': 'Parol',
      'kz': 'Құпия сөз',
      'id': 'Kata sandi',
      'tr': 'Şifre',
      'ms': 'Kata laluan',
      'bn': 'পাসওয়ার্ড',
      'en': 'Password',
      'fr': 'Mot de passe',
    },
    'register_continue': {
      'ru': 'ПРОДОЛЖИТЬ',
      'uz': 'DAVOM ETISH',
      'kz': 'ЖАЛҒАСТЫРУ',
      'id': 'LANJUTKAN',
      'tr': 'DEVAM ET',
      'ms': 'TERUSKAN',
      'bn': 'চালিয়ে যান',
      'en': 'CONTINUE',
      'fr': 'CONTINUER',
    },
    'login_title': {
      'ru': 'Вход',
      'uz': 'Kirish',
      'kz': 'Кіру',
      'id': 'Masuk',
      'tr': 'Giriş Yap',
      'ms': 'Log Masuk',
      'bn': 'লগ ইন',
      'en': 'Log In',
      'fr': 'Connexion',
    },
    'login_subtitle_1': {
      'ru': 'Добро пожаловать!',
      'uz': 'Xush kelibsiz!',
      'kz': 'Қош келдіңіз!',
      'id': 'Selamat datang!',
      'tr': 'Hoş geldiniz!',
      'ms': 'Selamat datang!',
      'bn': 'স্বাগতম!',
      'en': 'Welcome!',
      'fr': 'Bienvenue !',
    },
    'lang_loading': {
      'ru': 'Загружаем ваш язык…',
      'uz': 'Til yuklanmoqda…',
      'kz': 'Тіліңіз жүктелуде…',
      'id': 'Memuat bahasa Anda…',
      'tr': 'Diliniz yükleniyor…',
      'ms': 'Memuat bahasa anda…',
      'bn': 'আপনার ভাষা লোড হচ্ছে…',
      'en': 'Loading your language…',
      'fr': 'Chargement de votre langue…',
      'ar': 'جارٍ تحميل لغتك…',
    },
    'device_lang': {
      'ru':
          'Приложение использует системный язык устройства. Чтобы изменить язык, измените основной язык устройства в настройках.',
      'uz':
          'Ilova qurilmaning tizim tilidan foydalanadi. Tilni o‘zgartirish uchun qurilma sozlamalarida asosiy tilni o‘zgartiring.',
      'kk':
          'Қосымша құрылғының жүйелік тілін пайдаланады. Тілді өзгерту үшін құрылғы баптауларында негізгі тілді өзгертіңіз.',
      'tr':
          'Uygulama cihazın sistem dilini kullanır. Dili değiştirmek için cihaz ayarlarından ana dili değiştirin.',
      'id':
          'Aplikasi menggunakan bahasa sistem perangkat. Untuk mengubah bahasa, ubah bahasa utama di pengaturan perangkat.',
      'ms':
          'Aplikasi menggunakan bahasa sistem peranti. Untuk menukar bahasa, tukar bahasa utama dalam tetapan peranti.',
      'bn':
          'অ্যাপটি ডিভাইসের সিস্টেম ভাষা ব্যবহার করে। ভাষা পরিবর্তন করতে ডিভাইসের সেটিংসে প্রধান ভাষা পরিবর্তন করুন।',
      'en':
          'The app uses your device system language. To change the language, update the primary language in your device settings.',
      'fr':
          'L’application utilise la langue système de votre appareil. Pour changer de langue, modifiez la langue principale dans les paramètres de votre appareil.',
      'ar':
          'يستخدم التطبيق لغة النظام في جهازك. لتغيير اللغة، قم بتغيير اللغة الأساسية من إعدادات الجهاز.',
    },
    'login_subtitle_2': {
      'ru': 'Войдите в свой аккаунт и оставайтесь частью проекта',
      'uz': 'Hisobingizga kiring va loyiha bir qismi bo‘lib qoling',
      'kz': 'Аккаунтыңызға кіріп, жобаның бір бөлігі болып қала беріңіз',
      'id': 'Masuk ke akun Anda dan tetap menjadi bagian dari proyek',
      'tr': 'Hesabınıza giriş yapın ve projenin bir parçası olarak kalın',
      'ms':
          'Log masuk ke akaun anda dan kekal menjadi sebahagian daripada projek',
      'bn': 'আপনার অ্যাকাউন্টে প্রবেশ করুন এবং প্রকল্পের অংশ হয়ে থাকুন',
      'en': 'Log in to your account and stay connected to the project',
      'fr': 'Connectez-vous à votre compte et restez membre du projet',
    },
    'lang_title': {
      'ru': 'Выберите язык',
      'en': 'Choose language',
      'ar': 'اختر اللغة',
      'fr': 'Choisissez la langue',
      'tr': 'Dil seçin',
      'id': 'Pilih bahasa',
      'ms': 'Pilih bahasa',
      'uz': 'Tilni tanlang',
      'kk': 'Тілді таңдаңыз',
      'bn': 'ভাষা নির্বাচন করুন',
    },
    'umrah_certificate': {
      'ru': 'Сертификат Умры',
      'en': 'Umrah Certificate',
      'ar': 'شهادة العمرة',
      'fr': 'Certificat de Omra',
      'tr': 'Umre Sertifikası',
      'id': 'Sertifikat Umrah',
      'ms': 'Sijil Umrah',
      'uz': 'Umra sertifikati',
      'kk': 'Умра сертификаты',
      'bn': 'উমরাহ সনদ',
    },
    'auth_invalid': {
      'ru': 'Неверный email или пароль',
      'en': 'Invalid email or password',
      'ar': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'fr': 'Email ou mot de passe incorrect',
      'tr': 'E-posta veya şifre yanlış',
      'id': 'Email atau kata sandi salah',
      'ms': 'E-mel atau kata laluan salah',
      'uz': 'Email yoki parol noto‘g‘ri',
      'kk': 'Қате email немесе құпия сөз',
      'bn': 'ইমেইল বা পাসওয়ার্ড ভুল',
    },
    'auth_network': {
      'ru': 'Нет соединения с интернетом',
      'en': 'No internet connection',
      'ar': 'لا يوجد اتصال بالإنترنت',
      'fr': 'Pas de connexion internet',
      'tr': 'İnternet bağlantısı yok',
      'id': 'Tidak ada koneksi internet',
      'ms': 'Tiada sambungan internet',
      'uz': 'Internet aloqasi mavjud emas',
      'kk': 'Интернет байланысы жоқ',
      'bn': 'ইন্টারনেট সংযোগ নেই',
    },
    'auth_unknown': {
      'ru': 'Произошла неизвестная ошибка',
      'en': 'Unknown error occurred',
      'ar': 'حدث خطأ غير معروف',
      'fr': 'Erreur inconnue',
      'tr': 'Bilinmeyen hata oluştu',
      'id': 'Terjadi kesalahan tidak diketahui',
      'ms': 'Ralat tidak diketahui berlaku',
      'uz': 'Noma’lum xatolik yuz berdi',
      'kk': 'Белгісіз қате пайда болды',
      'bn': 'অজানা ত্রুটি ঘটেছে',
    },
    'profile_name_label': {
      'ru': 'Имя и фамилия',
      'en': 'Full name',
      'ar': 'الاسم الكامل',
      'fr': 'Nom et prénom',
      'tr': 'Ad ve soyad',
      'id': 'Nama lengkap',
      'ms': 'Nama penuh',
      'uz': 'Ism va familiya',
      'kk': 'Аты-жөні',
      'bn': 'পূর্ণ নাম',
    },
    'profile_country_label': {
      'ru': 'Гражданство',
      'en': 'Citizenship',
      'ar': 'الجنسية',
      'fr': 'Nationalité',
      'tr': 'Vatandaşlık',
      'id': 'Kewarganegaraan',
      'ms': 'Kewarganegaraan',
      'uz': 'Fuqaroligi',
      'kk': 'Азаматтығы',
      'bn': 'নাগরিকত্ব',
    },
    'continue_btn': {
      'ru': 'ПРОДОЛЖИТЬ',
      'en': 'CONTINUE',
      'ar': 'متابعة',
      'fr': 'CONTINUER',
      'tr': 'DEVAM ET',
      'id': 'LANJUTKAN',
      'ms': 'TERUSKAN',
      'uz': 'DAVOM ETISH',
      'kk': 'ЖАЛҒАСТЫРУ',
      'bn': 'চালিয়ে যান',
    },
    'lang_load_error': {
      'ru': 'Не удалось загрузить переводы. Проверь интернет и попробуй снова.',
      'en': 'Failed to load translations. Check internet and try again.',
      'ar': 'تعذر تحميل الترجمات. تحقق من الإنترنت وحاول مرة أخرى.',
      'fr':
          'Impossible de charger les traductions. Vérifiez Internet et réessayez.',
      'tr': 'Çeviriler yüklenemedi. İnterneti kontrol edip tekrar deneyin.',
      'id': 'Gagal memuat terjemahan. Periksa internet lalu coba lagi.',
      'ms': 'Gagal memuat terjemahan. Semak internet dan cuba lagi.',
      'uz': 'Tarjimalar yuklanmadi. Internetni tekshirib qayta urinib ko‘ring.',
      'kk': 'Аудармалар жүктелмеді. Интернетті тексеріп, қайта көріңіз.',
      'bn': 'অনুবাদ লোড করা যায়নি। ইন্টারনেট চেক করে আবার চেষ্টা করুন।',
    },
    'no_connection_title': {
      'ru': 'Нет соединения. Пожалуйста, проверьте интернет.',
      'en': 'No connection. Please check your internet.',
      'ar': 'لا يوجد اتصال. يرجى التحقق من الإنترنت.',
      'fr': 'Pas de connexion. Veuillez vérifier votre connexion Internet.',
      'tr': 'Bağlantı yok. Lütfen internetinizi kontrol edin.',
      'id': 'Tidak ada koneksi. Silakan periksa internet Anda.',
      'ms': 'Tiada sambungan. Sila semak internet anda.',
      'uz': 'Ulanish yo‘q. Iltimos, internetni tekshiring.',
      'kk': 'Қосылым жоқ. Интернетті тексеріңіз.',
      'bn': 'কোনো সংযোগ নেই। অনুগ্রহ করে আপনার ইন্টারনেট পরীক্ষা করুন।',
    },
    'retry_btn': {
      'ru': 'Повторить',
      'en': 'Retry',
      'ar': 'إعادة المحاولة',
      'fr': 'Réessayer',
      'tr': 'Tekrar dene',
      'id': 'Coba lagi',
      'ms': 'Cuba lagi',
      'uz': 'Qayta urinish',
      'kk': 'Қайталау',
      'bn': 'পুনরায় চেষ্টা করুন',
    },
    'login_email': {
      'ru': 'Email',
      'uz': 'Email',
      'kz': 'Email',
      'id': 'Email',
      'tr': 'E-posta',
      'ms': 'Email',
      'bn': 'ইমেইল',
      'en': 'Email',
      'fr': 'E-mail',
    },
    'login_password': {
      'ru': 'Пароль',
      'uz': 'Parol',
      'kz': 'Құпия сөз',
      'id': 'Kata sandi',
      'tr': 'Şifre',
      'ms': 'Kata laluan',
      'bn': 'পাসওয়ার্ড',
      'en': 'Password',
      'fr': 'Mot de passe',
    },
    'login_button': {
      'ru': 'ВОЙТИ',
      'uz': 'KIRISH',
      'kz': 'КІРУ',
      'id': 'MASUK',
      'tr': 'GİRİŞ',
      'ms': 'LOG MASUK',
      'bn': 'লগ ইন',
      'en': 'LOG IN',
      'fr': 'SE CONNECTER',
    },
    "loading_text": {
      "ru": "Загружаем ваш путь…",
      "uz": "Yo‘lingizni yuklayapmiz…",
      "kz": "Сіздің жолыңыз жүктелуде…",
      "id": "Memuat perjalanan Anda…",
      "tr": "Yolculuğunuz yükleniyor…",
      "ms": "Memuat perjalanan anda…",
      "bn": "আপনার পথ লোড করা হচ্ছে…",
      "en": "Loading your journey…",
      "fr": "Chargement de votre parcours…"
    },
    'login_policy_text': {
      'ru': 'Продолжая, вы соглашаетесь с Политикой конфиденциальности',
      'uz': 'Davom etish orqali siz Maxfiylik siyosatiga rozilik bildirasiz.',
      'kz': 'Жалғастыру арқылы сіз Құпиялылық саясатына келісесіз.',
      'id': 'Dengan melanjutkan, Anda menyetujui Kebijakan Privasi.',
      'tr': 'Devam ederek Gizlilik Politikasini kabul etmis olursunuz.',
      'ms': 'Dengan meneruskan, anda bersetuju dengan Dasar Privasi.',
      'bn': 'চালিয়ে গেলে আপনি গোপনীয়তা নীতিতে সম্মতি দিচ্ছেন।',
      'en': 'By continuing, you agree to the Privacy Policy.',
      'fr': 'En continuant, vous acceptez la Politique de confidentialite.',
    },
  };

  static String t(String key, String lang) {
    return _data[key]?[lang] ?? _data[key]?['en'] ?? key;
  }
}
